configured_endpoints: 43
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/anchor-browser%2Fanchorbrowser-ae160e81b91c0e432bf7ae488a5e5dda3adca494ae1b57c68c608d96b07c8f3a.yml
openapi_spec_hash: ba0a1ba7999a3aab0fb157ed278c7843
config_hash: d298aad6be232cc62488f7d124ac7fa9
