#!/usr/bin/env node
// Prepare the SDK build spec from the public OpenAPI spec.
//
// Reads spec/openapi.yaml (verbatim copy of the monorepo's docs/openapi.yaml)
// and spec/sdk-manifest.yaml, injects the SDK naming (operationId + a single
// class tag per operation), and writes spec/openapi-sdk.yaml — the file
// @hey-api/openapi-ts consumes. The public docs spec never needs
// SDK-specific annotations.
//
// Operations without a manifest entry get deterministic auto-derived names
// (class from the operation's first tag, method from verb + path) and are
// listed as warnings — add a manifest entry to override.

const fs = require('fs');
const path = require('path');
const YAML = require('yaml');

const specDir = path.resolve(__dirname, '..', '..', 'spec');
const spec = YAML.parse(fs.readFileSync(path.join(specDir, 'openapi.yaml'), 'utf8'));
const manifest = YAML.parse(fs.readFileSync(path.join(specDir, 'sdk-manifest.yaml'), 'utf8'));

const HTTP_METHODS = new Set(['get', 'post', 'put', 'patch', 'delete', 'head', 'options']);

const pascalCase = (s) =>
  s.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase()).replace(/^(.)/, (c) => c.toUpperCase());

function deriveName(method, p) {
  // 'get /v1/sessions/{session_id}/downloads' -> 'getV1SessionsBySessionIdDownloads'
  const parts = p
    .split('/')
    .filter(Boolean)
    .map((seg) => (seg.startsWith('{') ? 'By' + pascalCase(seg.slice(1, -1)) : pascalCase(seg)));
  return method + parts.join('');
}

const naming = manifest.naming ?? {};
const warnings = [];
const seenIds = new Map();

for (const [p, pathItem] of Object.entries(spec.paths ?? {})) {
  for (const [method, op] of Object.entries(pathItem)) {
    if (!HTTP_METHODS.has(method)) continue;
    const key = `${method} ${p}`;
    const entry = naming[key];

    let className, methodName;
    if (entry) {
      className = entry.class;
      methodName = entry.method;
    } else {
      className = pascalCase((op.tags?.[0] ?? 'Api').trim());
      methodName = deriveName(method, p);
      warnings.push(
        `  - ${key} -> ${className}.${methodName} (auto-derived; add to sdk-manifest.yaml to override)`,
      );
    }

    if (seenIds.has(methodName)) {
      console.error(
        `prepare-spec: duplicate method name '${methodName}' for '${key}' and '${seenIds.get(methodName)}'`,
      );
      process.exit(1);
    }
    seenIds.set(methodName, key);

    op.operationId = methodName;
    op.tags = [className];
  }
}

const out = path.join(specDir, 'openapi-sdk.yaml');
fs.writeFileSync(
  out,
  '# GENERATED by scripts/utils/prepare-spec.cjs from openapi.yaml + sdk-manifest.yaml — do not edit.\n' +
    YAML.stringify(spec, { aliasDuplicateObjects: false }),
);
console.log(`prepare-spec: wrote ${path.relative(process.cwd(), out)} (${seenIds.size} operations)`);
if (warnings.length > 0) {
  console.log(`prepare-spec: ${warnings.length} operations without manifest naming (auto-derived):`);
  console.log(warnings.join('\n'));
}
